name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Jacoco test report
      run: ./gradlew jacocoTestReport
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Archive Jacoco Test Report
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: app/build/reports/jacoco/jacocoTestReport

